### ISSUE TITLE
spinnaker_application and spinnaker_pipeline should be under job/put/params/trigger_params section

### ISSUE THREAD

**Issue by baychaservmware** [burdzwastaken/concourse-spinnaker-resource#11]
Current README is little bit confusing because it shows that we should put spinnaker_application and spinnaker_pipeline variables under resources/source section. However, based on my testing, we should put these two variables under jobs/put/params/trigger_params section. I will create a PR to fix this issue.

**Comment by burdzwastaken** [comment]
Hi @baychaservmware,

Sorry for the late reply!

This change was introduced as part of https://github.com/burdzwastaken/concourse-spinnaker-resource/pull/9. It needs to be placed in the resources/source section.

FYI I have been engaging with the pivotal team in making this resource more official and the first take can be found: https://github.com/pivotal-cf/spinnaker-resource
